slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_num_threads: 2

    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    use_lifecycle_manager: false

    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 12.0
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.1
    minimum_time_interval: 0.1

    do_loop_closing: false
    loop_search_maximum_distance: 3.0
    loop_match_minimum_response_fine: 0.35

    use_scan_matching: true
    use_scan_barycenter: true
    
    transform_timeout: 1.0
    tf_buffer_duration: 60.0	
